### ISSUE TITLE
没法启动

### ISSUE THREAD

**Issue by style6** [manycore-koolab/KoolSmart#10]
ker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/12/17 23:29:03 [emerg] 1#1: host not found in upstream "sit.coohom.com" in /etc/nginx/conf.d/default.conf:21
nginx: [emerg] host not found in upstream "sit.coohom.com" in /etc/nginx/conf.d/default.conf:21

**Comment by LuffyMonsterB** [comment]
看一下安装的版本，v0.1.1以上都解决了～

**Comment by style6** [comment]
确实安装的1.0版本，在加载项安装的，没看见更新的选项
