### ISSUE TITLE
use `mix-blend-mode: lighten` instead of `screen`

### ISSUE THREAD

**Issue by jasonslyvia** [manycore-koolab/KoolSmart#12]
by definition:

> screen: multiplies the background and the content then complements the result. This will result in content which is brighter than the background-color.

> lighten: the background is replaced with the content where the content is lighter.

using `screen` will cause the rendered home become lighter and lighter with more lights turning on, meanwhile using `lighten` will achieve the desiring result.

**Comment by LuffyMonsterB** [comment]
Thanks for the guide, we'll fix this in the next version!

**Comment by xiaoheitwo** [comment]
We have changed.
